// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-eLiGfKEv959IphvUDHsW2Mz7pEd-ej0',
    appId: '1:1084268488306:web:b7456c4b293b127583c4eb',
    messagingSenderId: '1084268488306',
    projectId: 'ecommerce-app-product-01',
    authDomain: 'ecommerce-app-product-01.firebaseapp.com',
    storageBucket: 'ecommerce-app-product-01.appspot.com',
    measurementId: 'G-LV9WL7BEM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALJWIyAclt_zFSVlX6G1inmFLjPL8LFVs',
    appId: '1:1084268488306:android:6bd8e792b2990d2283c4eb',
    messagingSenderId: '1084268488306',
    projectId: 'ecommerce-app-product-01',
    storageBucket: 'ecommerce-app-product-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjIrBXHap4DOgce93FOrXzraKv7Qj8nhg',
    appId: '1:1084268488306:ios:2d6692b638bf147983c4eb',
    messagingSenderId: '1084268488306',
    projectId: 'ecommerce-app-product-01',
    storageBucket: 'ecommerce-app-product-01.appspot.com',
    iosClientId: '1084268488306-2912iaigt2cdjp12fnu9t7bvpr629b4n.apps.googleusercontent.com',
    iosBundleId: 'com.jaydev.ecommerce.ecommerceApp',
  );

}